import { SCELLERIE_SIEGES_BAQUETS_CUIR_NOIR_DINAMICA, SCELLERIE_SIEGES_CONFORT_EN_CUIR_BRUN, SCELLERIE_SIEGES_CONFORT_EN_CUIR_NOIR } from "./option/scellerie";

export const SCELLERIE_OPTIONS = {
    label: 'Scellerie',
    slug: 'scellerie',
    uniqueOption: true,
    options: [
       SCELLERIE_SIEGES_BAQUETS_CUIR_NOIR_DINAMICA,
       SCELLERIE_SIEGES_CONFORT_EN_CUIR_NOIR,
       SCELLERIE_SIEGES_CONFORT_EN_CUIR_NOIR,
       SCELLERIE_SIEGES_CONFORT_EN_CUIR_BRUN
    ]
}